const REGISTRATION_STATUS_ENUM = {
  CHECKING: 0,
  NOT_REGISTERED: 1,
  REGISTERED: 2
};

const IPFS_ADD_STATUS_ENUM = {
  IDLE: 0,
  UPLOADING: 1,
  UPLOADED: 2
};

const IPFS_GET_STATUS_ENUM = {
  IDLE: 0,
  LOADING: 1,
  LOADED: 2,
  NOT_FOUND: 3
};

const ETH_TX_CONFIRM_ENUM = {
  IDLE: 0,
  SIGNING: 1,
  WAITING: 2,
  CONFIRMED: 3
}

module.exports = { REGISTRATION_STATUS_ENUM, IPFS_ADD_STATUS_ENUM, IPFS_GET_STATUS_ENUM, ETH_TX_CONFIRM_ENUM };
